# Generated by Django 5.2.7 on 2026-01-01 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_schedule_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='departure_datetime',
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
