# Generated by Django 5.2.7 on 2026-01-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_schedule_unique_together_remove_schedule_bus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.busassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('bus_assignment', 'seat_number')},
        ),
    ]
