# Generated by Django 5.2.7 on 2026-01-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_route_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('layout', models.JSONField()),
                ('total_seats', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.seatlayout'),
        ),
    ]
