# Generated by Django 5.2.7 on 2026-01-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seatlayout_booking_status_bus_seat_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="HELD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="seat_layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.seatlayout",
            ),
        ),
    ]
