# Generated by Django 5.2.7 on 2026-01-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_booking_status_alter_bus_seat_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=5),
        ),
    ]
