# Generated by Django 5.2.7 on 2026-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_busassignment_status_booking_hold_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
