# Generated by Django 5.2.7 on 2026-01-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_booking_hold_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='api.booking'),
        ),
    ]
