# Generated by Django 5.2.7 on 2026-01-22 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['HELD', 'CONFIRMED'])), fields=('bus_assignment', 'seat_number'), name='unique_active_seat_booking'),
        ),
    ]
