# Generated by Django 5.2.7 on 2026-01-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_booking_unique_together_alter_passenger_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='age',
            new_name='age_group',
        ),
    ]
