# Generated by Django 5.2.7 on 2026-01-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_booking_payment_reference_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
