# Generated by Django 5.2.7 on 2026-01-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='promo_code_used',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
