# Generated by Django 5.2.7 on 2026-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=40),
        ),
    ]
