# Generated by Django 5.2.7 on 2026-01-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='arrival_offset_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='departure_offset_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
